code-block-style:
  style: fenced
code-fence-style:
  style: backtick
emphasis-style:
  style: asterisk
fenced-code-language:
  allowed_languages:
  - bash
  - html
  - javascript
  - json
  - markdown
  - text
  - xml
  - yaml
  - go
  language_only: true
heading-style:
  style: atx
hr-style:
  style: "---"
line-length:
  strict: false
  code_blocks: false
link-image-style:
  autolink: false
  inline: false
  collapsed: false
  shortcut: false
no-duplicate-heading:
  siblings_only: true
ol-prefix:
  style: ordered
strong-style:
  style: asterisk
table-pipe-style:
  style: leading_and_trailing
ul-style:
  style: dash
